LibraryManagement/Workspace/application/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*
 * Static pages
 */
Route::get('/', 'HomeController@index')->name('home');
Route::get('/home', 'HomeController@index');
Route::get('/about', 'HomeController@show')->name('about');
Route::get('/borrow', 'HomeController@borrow');
Route::get('/return', 'HomeController@return');

/*
 * Login and Logout pages
 */
Auth::routes();
//Route::get('/login', 'Auth\LoginController@showLoginForm')->name("login");
//Route::post('/login', 'Auth\LoginController@login');
//Route::post('/logout', 'Auth\LoginController@logout')->name("logout");
//Route::get('/register', 'Auth\RegisterController@showRegisterForm')->name("register");
//Route::post('/register', 'Auth\RegisterController@register');

Route::middleware(['auth', 'decentralize'])->group(function () {
    //Book manager
    Route::resource('book', 'BookController');

    //Book's copy manager
    Route::get('/book/{book_id}/copy/create', ['as' => 'book.copy.create', 'uses' => 'BookCopyController@create']);
    Route::post('/book/{book_id}/copy', ['as' => 'book.copy.store', 'uses' => 'BookCopyController@store']);

    //Borrow book registration
    Route::get('/register-to-borrow-book/create',
        ['as' => 'book.borrow.register.create', 'uses' => 'BookBorrowRegistrationController@create']);
    Route::post('/register-to-borrow-book/store',
        ['as' => 'book.borrow.register.store', 'uses' => 'BookBorrowRegistrationController@store']);

    //Borrow book
    Route::get('/borrow-book/create', 'BorrowBookController@create')->name('borrow-book.create');
    Route::post('/borrow-book/store', 'BorrowBookController@store')->name('borrow-book.store');

    //Return book
    Route::get('/return-book/create', 'ReturnBookController@create')->name('return-book.create');
    Route::post('/return-book/store', 'ReturnBookController@store')->name('return-book.store');
});

LibraryManagement/Workspace/application/resources/views/partials/_footer.blade.php
<hr>
<p class="text-center">Copyright ISD.ICT.20171-07 - All Rights Reserved</p>

LibraryManagement/Workspace/application/resources/views/partials/_head.blade.php
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
<title>Library Management System @yield('title')</title> <!-- CHANGE THIS TITLE FOR EACH PAGE -->

<!-- Bootstrap -->
<link rel="stylesheet" href="{{ asset('css/bootstrap.min.css') }}">
<link rel="stylesheet" href="{{ asset('css/main.css') }}">

@yield('stylesheets')

<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
<script type="text/javascript" href="{{ asset('js/html5shiv.min.js')}}"></script>
<script type="text/javascript" href="{{ asset('js/respond.min.js') }}"></script>
<![endif]-->

LibraryManagement/Workspace/application/resources/views/partials/_javascript.blade.php
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

LibraryManagement/Workspace/application/resources/views/partials/_messages.blade.php
@if (Session::has('success'))
	
	<div class="alert alert-success" role="alert">
		<strong>Success:</strong> {{ Session::get('success') }}
	</div>

@endif

@if (count($errors) > 0)

	<div class="alert alert-danger" role="alert">
		<strong>Errors:</strong>
		<ul>
		@foreach ($errors->all() as $error)
			<li>{{ $error }}</li>
		@endforeach  
		</ul>
	</div>

@endif

LibraryManagement/Workspace/application/resources/views/partials/_nav.blade.php
<!-- Default Bootstrap Navbar -->
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand no-padding" href="/">
                <img class="main-logo" src="{{ asset('icon/logo.png') }}">
                <span class="sr-only">Library Management System</span>
            </a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="{{ Request::is('/')||Request::is('home') ? "active" : "" }}"><a href="{{ route('home') }}">Home</a></li>
                @role('admin')
                    <li class="{{ Request::is('user') ? "active" : "" }}"><a href="#">Users</a></li>
                @endrole
                @role(['admin', 'librarian'])
                    <li class="{{ Request::is('book') ? "active" : "" }}"><a href="{{ route('book.index') }}">Books</a></li>
                @endrole
                @role(['admin', 'librarian'])
                    <li class="{{ Request::is('borrow-book/create') ? "active" : "" }}">
                        <a href="{{ route('borrow-book.create') }}">Lent Books</a></li>
                @endrole
                @role(['admin', 'librarian'])
                    <li class="{{ Request::is('return-book/create') ? "active" : "" }}">
                        <a href="{{ route('return-book.create') }}">Return Books</a></li>
                @endrole
                <li class="{{ Request::is('about') ? "active" : "" }}"><a href="{{ route('about') }}">About</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <!-- Authentication Links -->
                @if (Auth::guest())
                    <li><a href="{{ route('login') }}">Login</a></li>
                    <li><a href="{{ route('register') }}">Register</a></li>
                @else
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                            {{ Auth::user()->name }} <span class="caret"></span>
                        </a>

                        <ul class="dropdown-menu" role="menu">
                            <li>
                                <a href="{{ route('logout') }}"
                                   onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                    Logout
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                    {{ csrf_field() }}
                                </form>
                            </li>
                        </ul>
                    </li>
                @endif
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>